### ISSUE TITLE
st.experimental_get_query_params will be removed after 2024-04-11

### ISSUE THREAD

**Issue by eguerrier** [hunkim/streamlit-google-oauth#13]
This is a warning I get when trying to execute the code with the google authentication.
st.experimental_get_query_params needs to be replaced by st.query_params.

https://github.com/hunkim/streamlit-google-oauth/blob/5feb84d2b8298f0a512a017bf7ffa9672b449342/streamlit_google_oauth/__init__.py#L82

**Comment by hunkim** [comment]
fixed it!
